### ISSUE TITLE
Unable to import because importDXFshape is not implemented in OpenSCAD2Dgeom

### ISSUE THREAD

**Issue by RickyDoug** [KeithSloan/OpenSCAD_Alt_Import#25]
File "/home/me/.local/share/FreeCAD/Mod/Alternate_OpenSCAD/./importAltCSG.py", line 1004, in processTextCmd
    from OpenSCAD2Dgeom import importDXFshape
<class 'ImportError'>: cannot import name 'importDXFshape' from 'OpenSCAD2Dgeom' (/home/me/.local/share/FreeCAD/Mod/Alternate_OpenSCAD/./OpenSCAD2Dgeom.py)

**Comment by KeithSloan** [comment]
line 1004 should  be from OpenSCAD2Dgeom import importDXFface.

Try latest version.

For Info from @mconsidine
